DROP TABLE IF EXISTS ENTRENADORES;
CREATE TABLE ENTRENADORES(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL);
INSERT INTO ENTRENADORES (NOMBRE) VALUES ('Pedro');
INSERT INTO ENTRENADORES (NOMBRE) VALUES ('Juan');
